package com.lyc.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lyc.callerinfo.model.db.HyBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HY_BEAN".
*/
public class HyBeanDao extends AbstractDao<HyBean, Long> {

    public static final String TABLENAME = "HY_BEAN";

    /**
     * Properties of entity HyBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property City = new Property(1, String.class, "city", false, "CITY");
        public final static Property Lng = new Property(2, String.class, "lng", false, "LNG");
        public final static Property Lat = new Property(3, String.class, "lat", false, "LAT");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Addr = new Property(5, String.class, "addr", false, "ADDR");
        public final static Property Tel = new Property(6, String.class, "tel", false, "TEL");
    }


    public HyBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HyBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HY_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"CITY\" TEXT," + // 1: city
                "\"LNG\" TEXT," + // 2: lng
                "\"LAT\" TEXT," + // 3: lat
                "\"NAME\" TEXT," + // 4: name
                "\"ADDR\" TEXT," + // 5: addr
                "\"TEL\" TEXT);"); // 6: tel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HY_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HyBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String lng = entity.getLng();
        if (lng != null) {
            stmt.bindString(3, lng);
        }
 
        String lat = entity.getLat();
        if (lat != null) {
            stmt.bindString(4, lat);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String addr = entity.getAddr();
        if (addr != null) {
            stmt.bindString(6, addr);
        }
 
        String tel = entity.getTel();
        if (tel != null) {
            stmt.bindString(7, tel);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HyBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String lng = entity.getLng();
        if (lng != null) {
            stmt.bindString(3, lng);
        }
 
        String lat = entity.getLat();
        if (lat != null) {
            stmt.bindString(4, lat);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String addr = entity.getAddr();
        if (addr != null) {
            stmt.bindString(6, addr);
        }
 
        String tel = entity.getTel();
        if (tel != null) {
            stmt.bindString(7, tel);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public HyBean readEntity(Cursor cursor, int offset) {
        HyBean entity = new HyBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // city
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lng
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // lat
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // addr
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // tel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HyBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setCity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLng(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLat(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTel(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HyBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HyBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HyBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
